### ISSUE TITLE
The coc size

### ISSUE THREAD

**Issue by vardenppp** [jherr/depth-of-field#4]
Great project! But i want to know why the full frame's coc is set to 0.029. Cause i calculate it like this：[36mm/6000(pixel)]*2 = 0.012. Can you tell me how you calculate the coc size？ Thanks！！！

**Comment by jherr** [comment]
As I recall I got these values from Wikipedia and they are hard-coded. https://en.wikipedia.org/wiki/Circle_of_confusion Feel free to PR, but please add why you think your values are more appropriate than these.

FWIW, this is not meant to be a precision tool. It's meant to be a way to learn how focal length, aperture size and distance to the subject relate to the depth of field.

**Comment by Dragon617** [comment]
Can you add options to adjust the camera height and theme height？

**Comment by jherr** [comment]
Maybe at some point. I don't really have a lot of time for this project right now.
